### ISSUE TITLE
Silex doesn't use the autoloader feature any more

### ISSUE THREAD

**Issue by FlorinPopaCodes** [mheap/Silex-Mandango#2]
The feature on the line https://github.com/mheap/Silex-Mandango/blob/master/src/SilexMandango/MandangoExtension.php#L96 must be rewriten to avoid causing an Exception in the newest versions of Silex.

**Comment by mheap** [comment]
The entire provider does not currently work, as it tries to access values in Pimple before they're registered. 

I'm planning on reworking the service provider as soon as I get chance, but for now the provider doesn't get past the point where it tries to access the configuration on line https://github.com/mheap/Silex-Mandango/blob/master/src/SilexMandango/MandangoExtension.php#L24

**Comment by FlorinPopaCodes** [comment]
I've moved all the code from the array from the lines 10 to 27 into the $app and removed the lines 96-99 from SilexMandango/MandangoExtension.php.

I've also added the "Model" namespace in PSR-0 in a custom location.

Needed a quick fix to get on working on using Silex.

p.s. Nice work.

**Comment by mheap** [comment]
Thanks, but I didn't do anything, I'm just the new maintainer :) You'll want to be saying thanks to @fate.

Any chance you could submit a pull request with your changes? Hacky and working is better than not working at all :)
